name: Run Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python (ou Node.js ou autre, selon votre projet)
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Pour Python
          # npm install  # Pour Node.js

      - name: Run linter
        run: |
          flake8 .  # Pour Python
          # eslint .  # Pour Node.js
