name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python (ou Node.js ou autre, selon votre projet)
        uses: actions/setup-python@v2  # Pour un projet Python, utilisez setup-python
        with:
          python-version: '3.12'  # Spécifiez la version que vous utilisez
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Utilisez npm install si vous êtes sur un projet Node.js

      - name: Run tests
        run: |
          pytest  # Pour Python
          # npm pytest  # Pour Node.js
